* ----------------------------------------------------------------------
* >>>
* FILENAME  : lf_info.inc
* DIRECTORY :
* PURPOSE   : Declaration of variables, constants and global (COMMON)
*             variables concerning internal information
* MODULE    : FORTRAN - INCLUDE FILE
* AUTOR     : JKR
* DATE      : 13.06.07
*
* <<<
* ----------------------------------------------------------------------
      CHARACTER*160 bf_info     ! info about bf-processes considered

      COMMON/LF_INFO/  bf_info
