
      FUNCTION SPLINE_INTEGRAL(X,Y,A,B,C,N,MODE)
      REAL X(N),Y(N),A(N),B(N),C(N)
C
C-----COMPUTATION OF CUBIC SPLINE INTEGRAL FROM X(1) TO X(N)
C-----IF MODE=1, COMPUTE SPLINE COEFFICIENTS FIRST
      IF (MODE.EQ.1) CALL SPLINE(X,Y,A,B,C,N)
      S=.0
      DO 10 I=1,N-1
      D=X(I+1)-X(I)
   10 S=S+D*(Y(I)+D*(A(I)/2.+D*(B(I)/3.+D*C(I)/4.)))
      SPLINE_INTEGRAL=S
C
      RETURN
      END
